<a href='https://numpy.org/doc/'> 🧮 Numpy Docs</a>
<img src="../supporting_items/NumPy_logo_2020.svg.png" width="200" height="100" />

# NumPy

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [61]:
import numpy as np

Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [62]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [63]:
np.array(my_list) # Conver a list to a array

array([1, 2, 3])

In [64]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] # 2d list
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [65]:
np.array(my_matrix) # Convert a 2d list to a numpy array which inturn behaves like a matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### 🔗 arange

Return evenly spaced values within a given interval.

In [66]:
for i in range(1,10):
  print(i)

1
2
3
4
5
6
7
8
9


In [67]:
np.arange(0,10) # arange is creating a numpy array within the defined range.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [68]:
np.arange(0,11,2) # Range 0 to 11 with step 2.

array([ 0,  2,  4,  6,  8, 10])

### 🔗 zeros and ones

Generate arrays of zeros or ones

In [69]:
np.zeros(3)

array([0., 0., 0.])

In [70]:
np.zeros((5,5)) # Create a 2d array with 5 rows and 5 columns

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [71]:
np.zeros((5,5,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [72]:
np.ones(3)

array([1., 1., 1.])

In [73]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 🔗linspace
Return evenly spaced numbers over a specified interval.

In [74]:
np.linspace(0,100,10) # Return 10 numbers evenly spaced between 0 to 100.
# By Default linespace returns 50 evenly spaced numbers.

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

In [75]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## 🔗 eye

Creates an identity matrix

In [76]:
np.eye(4) # Diagonal Matrix.

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## ✨Random

| Function | Distribution Type | Range | Example Result |
| :--- | :--- | :--- | :--- |
| **`rand()`** | Uniform | [0.0, 1.0) | `0.823...` |
| **`randn()`** | Standard Normal | $(-\infty, \infty)$ | `-0.451...` |
| **`randint()`** | Discrete Uniform | [low, high) | `7` |

Numpy also has lots of ways to create random number arrays:



### 🔗 rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [77]:
np.random.rand(2) # Randomly generate 2 numbers in a 1d array

array([0.70552798, 0.43212938])

In [78]:
np.random.rand(5,5) # Randomly generate a 2d Matrix of shape 5*5 and the number is anything between 0 and 1.

array([[0.72678814, 0.11820227, 0.0585933 , 0.903338  , 0.44969333],
       [0.83346673, 0.24396207, 0.19509669, 0.83655612, 0.83669872],
       [0.20184103, 0.64132751, 0.30773676, 0.94753451, 0.19971366],
       [0.76678344, 0.47410157, 0.12430086, 0.70328306, 0.01008974],
       [0.30666186, 0.71030856, 0.84770322, 0.93491144, 0.9970975 ]])

### 🔗randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [79]:
np.random.randn(30)

array([ 1.48247068, -0.40732459,  0.23854029, -0.38803903, -0.41795534,
        0.78532382,  0.11614172,  0.8715999 , -0.98193603, -0.12826441,
        2.04887456,  0.21102214, -0.27324571, -0.1652382 ,  1.40776293,
        0.38248951,  1.32120869, -2.08166922,  0.9235825 , -2.75713811,
        1.39873188,  0.33678159, -1.51307632, -0.61490314,  0.02867543,
        0.81889278, -0.13857622, -1.09816309, -0.67011595, -1.30193044])

In [114]:
np.random.randn(5,5)

array([[ 0.42610868,  0.64157794,  1.81390592,  0.45442598, -1.6989089 ],
       [-0.38404965,  1.2992619 , -0.98688612, -0.18957036,  0.32543163],
       [ 1.14366416, -0.64892524, -0.51115365, -1.01293534, -0.1766154 ],
       [ 0.27861148,  0.4301602 ,  0.13056605, -0.06999587,  0.48534516],
       [ 0.13036376, -0.01968394, -2.17447943,  1.16232905, -1.66434128]])

### 🔗randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [81]:
np.random.randint(90,100) # 1 random number between 1 to 100


92

In [82]:
np.random.randint(100) # Single argument in randint means the upper limit(exclusive)

2

In [83]:
np.random.randint(1,100,5) # NO. OF VALUES TO BE PRINTED BETWEEN 1 TO 100

array([60, 25, 58, 86, 54], dtype=int32)

## 🔗Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [84]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [85]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [86]:
ranarr

array([28, 42, 39, 35, 27, 12, 14, 48, 26, 43], dtype=int32)

## 🔗Reshape
Returns an array containing the same data with a new shape.

In [87]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 🔗 max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [88]:
ranarr

array([28, 42, 39, 35, 27, 12, 14, 48, 26, 43], dtype=int32)

In [89]:
ranarr.max()

np.int32(48)

In [90]:
ranarr.argmax() #gives the index of the maximum value in the array

np.int64(7)

In [91]:
ranarr.min()

np.int32(12)

In [92]:
ranarr.argmin() #gives the index of the minimum value in the array

np.int64(5)

## 🔗 Shape

Shape is an attribute that arrays have (not a method):

In [93]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [94]:
# Vector
arr.shape

(25,)

In [95]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [96]:
arr.reshape(1,25).shape

(1, 25)

In [97]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [98]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [99]:
arr.reshape(25,1).shape

(25, 1)

### 🔗dtype

You can also grab the data type of the object in the array:

In [100]:
arr.dtype

dtype('int64')

In [101]:
type(arr)

numpy.ndarray

# Great Job!

## Practice Question

In [102]:
X = np.array([ [ [5, 8, 3, 6], [9, 1, 7, 2], [4, 11, 13, 10] ], [ [14,
18, 12, 16], [19, 15, 17, 20], [21, 22, 23, 24] ], [ [25, 28, 26, 27],
[30, 29, 31, 32], [33, 34, 35, 36] ]])


In [103]:
# Q1. Find element 7
print(X[0][1][2]) # 2

7


In [104]:
# Q1. Find element 24
print(X[1][2][3]) # 2

24


In [105]:
# Q3. Extract entire first block
print(X[0])

[[ 5  8  3  6]
 [ 9  1  7  2]
 [ 4 11 13 10]]


In [106]:
# Q4. Extract second row from first block Expected: 9 1 7 2
print(X[0][1])

[9 1 7 2]


In [107]:
# Q5. Extract third column from second block Expected: 12 17 23
print(X[1][:,2])

[12 17 23]


In [108]:
# Q6. Extract sub-matrix: 15 17 22 23(?)
print(X[1][1:3,1:3])

[[15 17]
 [22 23]]


In [109]:
# Q7. Extract all elements greater than 30
print(X[X>30])

[31 32 33 34 35 36]


In [110]:
# Q8. Extract: 26 27 31 32
print(X[2][0:2,2:])

[[26 27]
 [31 32]]


In [111]:
#Q9. Extract first two blocks completely
print(X[0:2])

[[[ 5  8  3  6]
  [ 9  1  7  2]
  [ 4 11 13 10]]

 [[14 18 12 16]
  [19 15 17 20]
  [21 22 23 24]]]


In [112]:
# Q10. Extract: [[ 3 6] [12 16] [26 27]]
print(X[:,0,2:4])

[[ 3  6]
 [12 16]
 [26 27]]


### What is the difference between *X[2][1] vs X[1][1]

In [113]:
print(X)

[[[ 5  8  3  6]
  [ 9  1  7  2]
  [ 4 11 13 10]]

 [[14 18 12 16]
  [19 15 17 20]
  [21 22 23 24]]

 [[25 28 26 27]
  [30 29 31 32]
  [33 34 35 36]]]
