# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [27]:
import numpy as np

In [28]:
#Creating sample array
arr = np.arange(0,11)

In [29]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [30]:
#Get a value at an index
arr[8]

np.int64(8)

In [31]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [32]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [33]:
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [34]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [36]:
#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [37]:
# Notice the original array is also changed! This is because the slice is a view of the original array, not a copy. 
# Any changes made to the slice will affect the original array. 
print(id(arr)) 
print(id(slice_of_arr))


1894432215024
1894433191664


To find the actual "home" of the data, you check the .ctypes.data attribute or the .base attribute.
Since a slice is just a view, its id() (the Python object address) will be unique, but its data pointer will lead back to the original array's memory.
How to see the shared memory address
Here is the code to see that both point to the same physical spot in your RAM, in raw Markdown

Now note the changes also occur in our original array!

In [38]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [39]:
arr_test_copy = np.arange(0,11) 
arr_test_copy_1 = arr_test_copy #This is not a copy, this is a reference to the same array in memory
arr_test_copy_1[:]=99

print(arr_test_copy)
print(arr_test_copy_1)

SyntaxError: unterminated string literal (detected at line 1) (1902401317.py, line 1)

Data is not copied, it's a view of the original array! This avoids memory problems!

In [ ]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [4]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

#Show
print(arr_2d)

In [5]:
#Indexing row
arr_2d[1]


NameError: name 'arr_2d' is not defined

In [ ]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

In [ ]:
# Getting individual element value
arr_2d[1,0]

In [ ]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

In [ ]:
#Shape bottom row
arr_2d[2]

In [ ]:
#Shape bottom row
arr_2d[2,:]

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order,to show this, let's quickly build out a numpy array:

In [ ]:
#Set up matrix
arr2d = np.zeros((10,10))

In [ ]:
#Length of array
arr_length = arr2d.shape[1]

In [ ]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i

arr2d

Fancy indexing allows the following

In [ ]:
arr2d[[2,4,6,8]]

In [ ]:
#Allows in any order
arr2d[[6,4,2,7]]

## More Indexing Help
Indexing a 2d matrix can be a bit confusing at first, especially when you start to add in step size. Try google image searching NumPy indexing to fins useful images, like this one:

<img src= 'http://memory.osu.edu/classes/python/_images/numpy_indexing.png' width=500/>

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [ ]:
arr = np.arange(1,11)
arr

In [ ]:
arr > 4

In [ ]:
arr[arr > 4]

In [ ]:
bool_arr = arr>4

In [ ]:
bool_arr

In [ ]:
arr[bool_arr]

In [ ]:
arr[arr>2]

In [ ]:
x = 2
arr[arr>x]

# Great Job!
